use evdev::KeyCode;

pub(crate) const DEFAULT_SOUND_ON_EVENT: &str = "audio-volume-change";
pub(crate) const DEFAULT_SOUND_OFF_EVENT: &str = "audio-volume-muted";
pub(crate) const DEFAULT_SOUND_ON_WAV: &[u8] = include_bytes!("../unmute.wav");
pub(crate) const DEFAULT_SOUND_OFF_WAV: &[u8] = include_bytes!("../mute.wav");

pub(crate) const CONFIG_FILE_NAME: &str = "config.toml";
pub(crate) const CONFIG_DIR_NAME: &str = "pttkey";
pub(crate) const CONFIG_BACKUP_NAME: &str = ".pttkey-config.toml";

macro_rules! key_map {
    ($($key:ident),+ $(,)?) => {
        &[
            $(
                (stringify!($key), KeyCode::$key)
            ),+
        ]
    };
}

pub(crate) const SUPPORTED_KEYS: &[(&str, KeyCode)] = key_map![
    // Mouse buttons,
    BTN_LEFT,
    BTN_RIGHT,
    BTN_MIDDLE,
    BTN_SIDE,
    BTN_EXTRA,
    BTN_FORWARD,
    BTN_BACK,
    // Letters,
    KEY_A,
    KEY_B,
    KEY_C,
    KEY_D,
    KEY_E,
    KEY_F,
    KEY_G,
    KEY_H,
    KEY_I,
    KEY_J,
    KEY_K,
    KEY_L,
    KEY_M,
    KEY_N,
    KEY_O,
    KEY_P,
    KEY_Q,
    KEY_R,
    KEY_S,
    KEY_T,
    KEY_U,
    KEY_V,
    KEY_W,
    KEY_X,
    KEY_Y,
    KEY_Z,
    // Numbers row,
    KEY_0,
    KEY_1,
    KEY_2,
    KEY_3,
    KEY_4,
    KEY_5,
    KEY_6,
    KEY_7,
    KEY_8,
    KEY_9,
    // Function keys,
    KEY_F1,
    KEY_F2,
    KEY_F3,
    KEY_F4,
    KEY_F5,
    KEY_F6,
    KEY_F7,
    KEY_F8,
    KEY_F9,
    KEY_F10,
    KEY_F11,
    KEY_F12,
    KEY_F13,
    KEY_F14,
    KEY_F15,
    KEY_F16,
    KEY_F17,
    KEY_F18,
    KEY_F19,
    KEY_F20,
    KEY_F21,
    KEY_F22,
    KEY_F23,
    KEY_F24,
    // Modifiers and whitespace,
    KEY_LEFTCTRL,
    KEY_RIGHTCTRL,
    KEY_LEFTSHIFT,
    KEY_RIGHTSHIFT,
    KEY_LEFTALT,
    KEY_RIGHTALT,
    KEY_LEFTMETA,
    KEY_RIGHTMETA,
    KEY_CAPSLOCK,
    KEY_TAB,
    KEY_SPACE,
    KEY_ENTER,
    KEY_ESC,
    KEY_BACKSPACE,
    // Navigation,
    KEY_UP,
    KEY_DOWN,
    KEY_LEFT,
    KEY_RIGHT,
    KEY_HOME,
    KEY_END,
    KEY_PAGEUP,
    KEY_PAGEDOWN,
    KEY_INSERT,
    KEY_DELETE,
    // Punctuation,
    KEY_MINUS,
    KEY_EQUAL,
    KEY_LEFTBRACE,
    KEY_RIGHTBRACE,
    KEY_BACKSLASH,
    KEY_SEMICOLON,
    KEY_APOSTROPHE,
    KEY_GRAVE,
    KEY_COMMA,
    KEY_DOT,
    KEY_SLASH,
    // Numpad,
    KEY_NUMLOCK,
    KEY_KPSLASH,
    KEY_KPASTERISK,
    KEY_KPMINUS,
    KEY_KPPLUS,
    KEY_KPENTER,
    KEY_KP0,
    KEY_KP1,
    KEY_KP2,
    KEY_KP3,
    KEY_KP4,
    KEY_KP5,
    KEY_KP6,
    KEY_KP7,
    KEY_KP8,
    KEY_KP9,
    KEY_KPDOT,
    // Media,
    KEY_MUTE,
    KEY_VOLUMEDOWN,
    KEY_VOLUMEUP,
    KEY_PLAYPAUSE,
    KEY_NEXTSONG,
    KEY_PREVIOUSSONG,
    KEY_STOPCD,
];
